use anyhow::Result;
use std::path::Path;
use std::fs;

pub fn generate(name: &str, output: &Path, plugin_type: &str) -> Result<()> {
    let plugin_dir = output.join(format!("plugin-{}", name));
    fs::create_dir_all(&plugin_dir)?;
    
    // Create Cargo.toml
    let cargo_toml = format!(
r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
"#, name);
    
    fs::write(plugin_dir.join("Cargo.toml"), cargo_toml)?;
    
    // Create src directory
    let src_dir = plugin_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    
    // Generate plugin code based on type
    let plugin_code = match plugin_type {
        "filter" => generate_filter_plugin(name),
        "transform" => generate_transform_plugin(name),
        "aggregator" => generate_aggregator_plugin(name),
        _ => generate_filter_plugin(name), // Default to filter
    };
    
    fs::write(src_dir.join("lib.rs"), plugin_code)?;
    
    // Create README
    let readme = format!(
r#"# {} Plugin

Type: {}

## Building

```bash
cargo build --target wasm32-wasip1 --release
```

## Testing

```bash
cargo test
```

Generated by zenith-codegen
"#, name, plugin_type);
    
    fs::write(plugin_dir.join("README.md"), readme)?;
    
    Ok(())
}

fn generate_filter_plugin(name: &str) -> String {
    format!(
r#"// {} Filter Plugin
// Auto-generated by zenith-codegen

#[no_mangle]
pub extern "C" fn on_event(source_id: u32, seq_no: u64) -> i32 {{
    // Filter logic here
    // Return 1 to accept, 0 to drop
    
    // Example: Accept only even sequence numbers
    if seq_no % 2 == 0 {{
        1
    }} else {{
        0
    }}
}}

#[no_mangle]
pub extern "C" fn init() -> i32 {{
    // Initialization logic
    0
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_filter() {{
        assert_eq!(on_event(1, 2), 1);
        assert_eq!(on_event(1, 3), 0);
    }}
}}
"#, name)
}

fn generate_transform_plugin(name: &str) -> String {
    format!(
r#"// {} Transform Plugin
// Auto-generated by zenith-codegen

#[no_mangle]
pub extern "C" fn transform(source_id: u32, seq_no: u64, value: i64) -> i64 {{
    // Transform logic here
    // Example: multiply by 2
    value * 2
}}

#[no_mangle]
pub extern "C" fn init() -> i32 {{
    0
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_transform() {{
        assert_eq!(transform(1, 1, 10), 20);
    }}
}}
"#, name)
}

fn generate_aggregator_plugin(name: &str) -> String {
    format!(
r#"// {} Aggregator Plugin
// Auto-generated by zenith-codegen

static mut COUNT: u64 = 0;
static mut SUM: i64 = 0;

#[no_mangle]
pub extern "C" fn on_event(source_id: u32, seq_no: u64) -> i32 {{
    unsafe {{
        COUNT += 1;
        SUM += seq_no as i64;
    }}
    1
}}

#[no_mangle]
pub extern "C" fn get_count() -> u64 {{
    unsafe {{ COUNT }}
}}

#[no_mangle]
pub extern "C" fn get_avg() -> i64 {{
    unsafe {{
        if COUNT > 0 {{
            SUM / COUNT as i64
        }} else {{
            0
        }}
    }}
}}

#[no_mangle]
pub extern "C" fn reset() {{
    unsafe {{
        COUNT = 0;
        SUM = 0;
    }}
}}
"#, name)
}
